server:
  port: 8081

spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 18110116114421
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true